sudo: required
services:
  - docker

before_install:
  - docker build -t gmuellercole/docker_thing -f Dockerfile.dev .

script:
  # by default 'npm run test' waits for input from user, adding
  # '-- --coverage' will cause it to exit when the tests finish
  #- docker run gmuellercole/docker_thing npm run test -- --coverage